In [1]:
import pandas as pd

df = pd.read_csv('data/great_all.csv')
#df = pd.read_csv('data/synthetic_all.csv')
df.head()

   year  month  day  latitude  longitude   dhw    sst
0  1985      4    1   -18.175    147.425  1.51  27.55
1  1985      4    2   -18.175    147.425  1.51  27.49
2  1985      4    3   -18.175    147.425  1.51  27.47
3  1985      4    4   -18.175    147.425  1.51  27.86
4  1985      4    5   -18.175    147.425  1.51  27.81

In [2]:

"""
def days_away_from_jan_1st(date_str):
    date = pd.to_datetime(date_str)
    jan_1st = date.normalize().replace(month=1, day=1)
    dec_31st = date.normalize().replace(month=12, day=31)
    return min((date - jan_1st).days, (dec_31st - date).days)


# map to a 0-1 scale
def scale_dhw(date_str, max_days=181.0, max_dhw=4.0):
    days = days_away_from_jan_1st(date_str)
    return max_dhw*(max_days - days) / max_days
""" 
# the actual data series we want to use has year, month, and day columns

def days_away_from_jan_1st(year, month, day):
    date = pd.to_datetime(f"{year}-{month}-{day}")
    jan_1st = date.normalize().replace(month=1, day=1)
    dec_31st = date.normalize().replace(month=12, day=31)
    return min((date - jan_1st).days, (dec_31st - date).days)

def scale_dhw(year, month, day, max_days=181.0, max_dhw=4.0):
    days = days_away_from_jan_1st(year, month, day)
    return max(0.0, max_dhw*(max_days - days) / max_days)

In [3]:
synthetic = df.copy()
synthetic['dhw'] = synthetic.apply(lambda x: scale_dhw(int(x['year']), int(x['month']), int(x['day'])), axis=1)
#synthetic['dhw'] = 0.0
synthetic.head()

   year  month  day  latitude  longitude       dhw    sst
0  1985      4    1   -18.175    147.425  2.011050  27.55
1  1985      4    2   -18.175    147.425  1.988950  27.49
2  1985      4    3   -18.175    147.425  1.966851  27.47
3  1985      4    4   -18.175    147.425  1.944751  27.86
4  1985      4    5   -18.175    147.425  1.922652  27.81

In [4]:
synthetic.to_csv('data/synthetic_all.csv', index=False)
#synthetic.to_csv('data/synthetic_all_zero.csv', index=False)